# Feature Selection

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import os
import sklearn as sklearn

In [2]:
path = os.getcwd()

print(path)
os.chdir('C:\\bb\\airbnb')

df = pd.read_csv(".\\data\\FF_train_clean_enriched1.csv")
df.head()

C:\bb\airbnb

,week_num_1,week_num_10,week_num_11,week_num_12,week_num_13,week_num_14,week_num_15,week_num_16,week_num_17,week_num_18,...,accommodates.norm_Two,accommodates.norm_Three,accommodates.norm_Fore,accommodates.norm_Five,accommodates.norm_More,host_about_len,description_len,summary_len,total_amenities,price_per_person
0,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,81,255,255,18,2.467237
1,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,81,255,255,18,2.467237
2,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,81,255,255,18,2.467237
3,0,0,0,0,0,1,0,0,0,0,...,1,0,0,0,0,81,255,255,18,2.467237
4,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,255,255,255,18,2.232954

In [147]:
## Remove strings

string_features = ['summary','space', 'description', 'neighborhood_overview','notes','transit','host_about','amenities']

df=df.drop(string_features, axis=1)

In [182]:
df['host_is_superhost'] = df['host_is_superhost'].astype('category').cat.codes
df['host_identity_verified'] = df['host_identity_verified'].astype('category').cat.codes
df['neighbourhood_cleansed'] = df['neighbourhood_cleansed'].astype('category').cat.codes
df['zipcode'] = df['zipcode'].astype('category').cat.codes
df['instant_bookable'] = df['instant_bookable'].astype('category').cat.codes
df['cancellation_policy'] = df['cancellation_policy'].astype('category').cat.codes
df['require_guest_profile_picture'] = df['require_guest_profile_picture'].astype('category').cat.codes
df['require_guest_phone_verification'] = df['require_guest_phone_verification'].astype('category').cat.codes
df['occupied_cat'] = df['occupied_cat'].astype('category').cat.codes
df['is_location_exact'] = df['is_location_exact'].astype('category').cat.codes
df['property_type'] = df['property_type'].astype('category').cat.codes
df['room_type'] = df['room_type'].astype('category').cat.codes
df['bed_type'] = df['bed_type'].astype('category').cat.codes
df['bathrooms'] = df['bathrooms'].astype('category').cat.codes
df['bedrooms'] = df['bedrooms'].astype('category').cat.codes
df['beds'] = df['beds'].astype('category').cat.codes
df['security_deposit'] = df['security_deposit'].astype('category').cat.codes
df['cleaning_fee'] = df['cleaning_fee'].astype('category').cat.codes
df['guests_included'] = df['guests_included'].astype('category').cat.codes
df['extra_people'] = df['extra_people'].astype('category').cat.codes
df['minimum_nights'] = df['minimum_nights'].astype('category').cat.codes
df['maximum_nights'] = df['maximum_nights'].astype('category').cat.codes
df['number_of_reviews'] = df['number_of_reviews'].astype('category').cat.codes
df['review_scores_accuracy'] = df['review_scores_accuracy'].astype('category').cat.codes
df['review_scores_cleanliness'] = df['review_scores_cleanliness'].astype('category').cat.codes
df['review_scores_checkin'] = df['review_scores_checkin'].astype('category').cat.codes
df['review_scores_communication'] = df['review_scores_communication'].astype('category').cat.codes
df['review_scores_location'] = df['review_scores_location'].astype('category').cat.codes
df['review_scores_value'] = df['review_scores_value'].astype('category').cat.codes
df['calculated_host_listings_count'] = df['calculated_host_listings_count'].astype('category').cat.codes
df['reviews_per_month'] = df['reviews_per_month'].astype('category').cat.codes
df['accommodates.norm'] = df['accommodates.norm'].astype('category').cat.codes

In [149]:
df.bed_type.value_counts()

4    174149
2       809
3       683
0       452
1       358
Name: bed_type, dtype: int64

In [150]:
## Drop not needed columns

In [174]:
df = df.drop(['X','listing_id'], axis=1)

KeyError: "['X' 'listing_id'] not found in axis"

In [152]:
df.shape
df[df.columns[~df.columns.isin(['C','D'])]]

(176451, 40)

In [198]:
varSel = pd.DataFrame({'Variable': df.columns[~df.columns.isin(['occupied_cat'])]})
varSel.head()

            Variable
0           week_num
1          avg_price
2          min_price
3          max_price
4  host_is_superhost

## Univariable Analysis

In [154]:
import pyMechkar as pm

In [155]:
from pyMechkar import analysis as apm

In [156]:
df.columns

Index(['week_num', 'avg_price', 'min_price', 'max_price', 'host_is_superhost',
       'host_identity_verified', 'neighbourhood_cleansed', 'zipcode',
       'latitude', 'longitude', 'is_location_exact', 'property_type',
       'room_type', 'accommodates', 'bathrooms', 'bedrooms', 'beds',
       'bed_type', 'security_deposit', 'cleaning_fee', 'guests_included',
       'extra_people', 'minimum_nights', 'maximum_nights', 'number_of_reviews',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'instant_bookable',
       'cancellation_policy', 'require_guest_profile_picture',
       'require_guest_phone_verification', 'calculated_host_listings_count',
       'reviews_per_month', 'host_seniority', 'occupied_cat',
       'accommodates.norm'],
      dtype='object')

In [157]:
df.head()

,week_num,avg_price,min_price,max_price,host_is_superhost,host_identity_verified,neighbourhood_cleansed,zipcode,latitude,longitude,...,review_scores_value,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month,host_seniority,occupied_cat,accommodates.norm
0,12,4.934474,4.934474,4.934474,1,0,16,8,37.76697,-122.42404,...,3,1,0,0,0,1,6,4,0,5
1,13,4.934474,4.934474,4.934474,1,0,16,8,37.76697,-122.42404,...,3,1,0,0,0,1,6,4,1,5
2,11,4.934474,4.934474,4.934474,1,0,16,8,37.76697,-122.42404,...,3,1,0,0,0,1,6,4,2,5
3,14,4.934474,4.934474,4.934474,1,0,16,8,37.76697,-122.42404,...,3,1,0,0,0,1,6,4,2,5
4,11,4.465908,4.465908,4.465908,0,1,1,14,37.73612,-122.42110,...,1,0,3,0,0,2,0,10,0,5

In [158]:
tab1 = apm.Table1(x=['week_num', 'avg_price', 'min_price', 'max_price', 'host_is_superhost',
       'host_identity_verified', 'neighbourhood_cleansed', 'zipcode',
       'latitude', 'longitude', 'is_location_exact', 'property_type',
       'room_type', 'accommodates', 'bathrooms', 'bedrooms', 'beds',
       'bed_type', 'security_deposit', 'cleaning_fee', 'guests_included',
       'extra_people', 'minimum_nights', 'maximum_nights', 'number_of_reviews',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'instant_bookable',
       'cancellation_policy', 'require_guest_profile_picture',
       'require_guest_phone_verification', 'calculated_host_listings_count',
       'reviews_per_month', 'host_seniority', 'accommodates.norm'], 
                  y="occupied_cat", data=df)

Begining analysis...
Factorizing... please wait
***************************************
["The variable neighbourhood_cleansed doesn't exists in the dataset... avoiding", "The variable zipcode doesn't exists in the dataset... avoiding", "The variable reviews_per_month doesn't exists in the dataset... avoiding"]
[****************************************
[****************************************
[****************************************
['Unable to calcualte the Fisher exact test for variables neighbourhood_cleansed and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables zipcode and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type and occupied_cat... The p-value may be incorrect']
------ Finished in 28.899734258651733econds -----

In [159]:
tab1

,Variables,Categories,Population,Category_0,Category_1,Category_2,p_value
0,Individuals,n,176451,60510,81594,34347,NaN
1,week_num,Mean (SD),28.10 ( 15.80),26.40 ( 14.20),29.70 ( 17.10),27.20 ( 14.90),0.0
2,week_num,Median (IQR),28.00 ( 14.00- 43.00),26.00 ( 14.00- 38.00),31.00 ( 15.00- 47.00),27.00 ( 14.00- 40.00),NaN
4,avg_price,Mean (SD),5.10 ( 0.70),5.10 ( 0.70),5.00 ( 0.70),5.10 ( 0.70),0.0
5,avg_price,Median (IQR),5.00 ( 4.60- 5.50),5.10 ( 4.70- 5.50),5.00 ( 4.60- 5.50),5.00 ( 4.60- 5.50),NaN
7,min_price,Mean (SD),5.00 ( 0.70),5.10 ( 0.70),5.00 ( 0.70),5.00 ( 0.70),0.0
8,min_price,Median (IQR),5.00 ( 4.60- 5.40),5.10 ( 4.60- 5.50),5.00 ( 4.50- 5.50),4.90 ( 4.60- 5.40),NaN
10,max_price,Mean (SD),5.10 ( 0.70),5.10 ( 0.70),5.10 ( 0.80),5.20 ( 0.70),0.0
11,max_price,Median (IQR),5.10 ( 4.70- 5.60),5.10 ( 4.70- 5.50),5.00 ( 4.60- 5.60),5.10 ( 4.70- 5.60),NaN
13,host_is_superhost,0,"110,863.00 ( 62.80%)","35,085.00 ( 58.00%)","60,120.00 ( 73.70%)","15,658.00 ( 45.60%)",NaN
14,host_is_superhost,1,"65,588.00 ( 37.20%)","25,425.00 ( 42.00%)","21,474.00 ( 26.30%)","18,689.00 ( 54.40%)",0.0
15,host_identity_verified,1,"95,665.00 ( 54.20%)","28,992.00 ( 47.90%)","49,615.00 ( 60.80%)","17,058.00 ( 49.70%)",NaN
16,host_identity_verified,0,"80,786.00 ( 45.80%)","31,518.00 ( 52.10%)","31,979.00 ( 39.20%)","17,289.00 ( 50.30%)",0.0
17,latitude,Mean (SD),37.80 ( 0.00),37.80 ( 0.00),37.80 ( 0.00),37.80 ( 0.00),0.0
18,latitude,Median (IQR),37.80 ( 37.80- 37.80),37.80 ( 37.80- 37.80),37.80 ( 37.80- 37.80),37.80 ( 37.70- 37.80),NaN
20,longitude,Mean (SD),-122.40 ( 0.00),-122.40 ( 0.00),-122.40 ( 0.00),-122.40 ( 0.00),0.0
21,longitude,Median (IQR),-122.40 ( -122.40- -122.40),-122.40 ( -122.40- -122.40),-122.40 ( -122.40- -122.40),-122.40 ( -122.40- -122.40),NaN
23,is_location_exact,1,"149,070.00 ( 84.50%)","48,855.00 ( 80.70%)","70,527.00 ( 86.40%)","29,688.00 ( 86.40%)",NaN
24,is_location_exact,0,"27,381.00 ( 15.50%)","11,655.00 ( 19.30%)","11,067.00 ( 13.60%)","4,659.00 ( 13.60%)",0.0
25,property_type,Apartment,"73,590.00 ( 41.70%)","26,504.00 ( 43.80%)","36,561.00 ( 44.80%)","10,525.00 ( 30.60%)",NaN
26,property_type,House,"51,108.00 ( 29.00%)","14,895.00 ( 24.60%)","25,189.00 ( 30.90%)","11,024.00 ( 32.10%)",0.0
27,property_type,Condominium,"14,820.00 ( 8.40%)","5,517.00 ( 9.10%)","6,333.00 ( 7.80%)","2,970.00 ( 8.60%)",NaN
28,property_type,Guest suite,"10,360.00 ( 5.90%)","4,332.00 ( 7.20%)","1,846.00 ( 2.30%)","4,182.00 ( 12.20%)",NaN
29,property_type,Boutique hotel,"5,855.00 ( 3.30%)","2,805.00 ( 4.60%)","1,745.00 ( 2.10%)","1,305.00 ( 3.80%)",NaN
30,property_type,Hotel,"3,225.00 ( 1.80%)",NaN,NaN,"1,015.00 ( 3.00%)",NaN
31,property_type,Other,"14,696.00 ( 8.30%)","3,422.00 ( 5.70%)","7,192.00 ( 8.80%)","2,613.00 ( 7.60%)",NaN
32,room_type,0,"95,660.00 ( 54.20%)","39,412.00 ( 65.10%)","39,482.00 ( 48.40%)","16,766.00 ( 48.80%)",NaN
33,room_type,2,"71,138.00 ( 40.30%)","19,205.00 ( 31.70%)","35,690.00 ( 43.70%)","16,243.00 ( 47.30%)",0.0
34,room_type,3,"8,119.00 ( 4.60%)","1,330.00 ( 2.20%)","5,850.00 ( 7.20%)",939.00 ( 2.70%),NaN
35,room_type,1,"1,534.00 ( 0.90%)",563.00 ( 0.90%),572.00 ( 0.70%),399.00 ( 1.20%),NaN
...,...,...,...,...,...,...,...
103,review_scores_value,3,"68,070.00 ( 38.60%)","25,472.00 ( 42.10%)","26,387.00 ( 32.30%)","16,211.00 ( 47.20%)",NaN
104,review_scores_value,1,"60,878.00 ( 34.50%)","17,438.00 ( 28.80%)","29,994.00 ( 36.80%)","13,446.00 ( 39.10%)",0.0
105,review_scores_value,2,"35,442.00 ( 20.10%)","14,128.00 ( 23.30%)","17,857.00 ( 21.90%)","3,457.00 ( 10.10%)",NaN
106,review_scores_value,0,"12,061.00 ( 6.80%)","3,472.00 ( 5.70%)","7,356.00 ( 9.00%)","1,233.00 ( 3.60%)",NaN
107,instant_bookable,0,"103,425.00 ( 58.60%)","30,388.00 ( 50.20%)","54,715.00 ( 67.10%)","18,322.00 ( 53.30%)",NaN
108,instant_bookable,1,"73,026.00 ( 41.40%)","30,122.00 ( 49.80%)","26,879.00 ( 32.90%)","16,025.00 ( 46.70%)",0.0
109,cancellation_policy,3,"57,606.00 ( 32.60%)","27,206.00 ( 45.00%)","16,726.00 ( 20.50%)","13,674.00 ( 39.80%)",NaN
110,cancellation_policy,1,"57,159.00 ( 32.40%)","19,102.00 ( 31.60%)","23,837.00 ( 29.20%)","14,220.00 ( 41.40%)",0.0
111,cancellation_policy,0,"37,282.00 ( 21.10%)","13,237.00 ( 21.90%)","17,815.00 ( 21.80%)","6,230.00 ( 18.10%)",NaN
112,cancellation_policy,2,"22,021.00 ( 12.50%)",51.00 ( 0.10%),"21,958.00 ( 26.90%)",12.00 ( 0.00%),NaN
113,cancellation_policy,4,"1,790.00 ( 1.00%)",623.00 ( 1.00%),"1,015.00 ( 1.20%)",152.00 ( 0.40%),NaN
114,cancellation_policy,5,593.00 ( 0.30%),291.00 ( 0.50%),243.00 ( 0.30%),59.00 ( 0.20%),NaN
115,require_guest_profile_picture,0,"167,773.00 ( 95.10%)","58,048.00 ( 95.90%)","76,805.00 ( 94.10%)","32,920.00 ( 95.80%)",NaN
116,require_guest_profile_picture,1,"8,678.00 ( 4.90%)","2,462.00 ( 4.10%)","4,789.00 ( 5.90%)","1,427.00 ( 4.20%)",0.0
117,require_guest_phone_verification,0,"165,584.00 ( 93.80%)","57,239.00 ( 94.60%)","75,840.00 ( 92.90%)","32,505.00 ( 94.60%)",NaN
118,require_guest_phone_verification,1,"10,867.00 ( 6.20%)","3,271.00 ( 5.40%)","5,754.00 ( 7.10%)","1,842.00 ( 5.40%)",0.0
119,calculated_host_listings_count,1,"65,632.00 ( 37.20%)","19,790.00 ( 32.70%)","31,902.00 ( 39.10%)","13,940.00 ( 40.60%)",NaN
120,calculated_host_listings_count,3,"51,779.00 ( 29.30%)","15,591.00 ( 25.80%)","24,783.00 ( 30.40%)","11,405.00 ( 33.20%)",0.0
121,calculated_host_listings_count,4,"26,074.00 ( 14.80%)","8,367.00 ( 13.80%)","13,283.00 ( 16.30%)","4,424.00 ( 12.90%)",NaN
122,calculated_host_listings_count,2,"19,107.00 ( 10.80%)","7,958.00 ( 13.20%)","8,156.00 ( 10.00%)","2,993.00 ( 8.70%)",NaN
123,calculated_host_listings_count,5,"12,125.00 ( 6.90%)","7,820.00 ( 12.90%)","2,914.00 ( 3.60%)","1,391.00 ( 4.00%)",NaN
124,calculated_host_listings_count,0,"1,734.00 ( 1.00%)",984.00 ( 1.60%),556.00 ( 0.70%),194.00 ( 0.60%),NaN
125,host_seniority,Mean (SD),4.10 ( 2.50),4.60 ( 2.50),3.50 ( 2.30),4.60 ( 2.50),0.0
126,host_seniority,Median (IQR),4.00 ( 2.00- 6.00),5.00 ( 3.00- 7.00),3.00 ( 2.00- 5.00),5.00 ( 3.00- 6.00),NaN
128,accommodates.norm,5,"82,868.00 ( 47.00%)","29,762.00 ( 49.20%)","36,850.00 ( 45.20%)","16,256.00 ( 47.30%)",NaN
129,accommodates.norm,1,"34,682.00 ( 19.70%)","12,092.00 ( 20.00%)","15,424.00 ( 18.90%)","7,166.00 ( 20.90%)",0.0
130,accommodates.norm,2,"20,953.00 ( 11.90%)","7,548.00 ( 12.50%)","9,352.00 ( 11.50%)","4,053.00 ( 11.80%)",NaN
131,accommodates.norm,3,"15,682.00 ( 8.90%)","3,838.00 ( 6.30%)","9,486.00 ( 11.60%)","2,358.00 ( 6.90%)",NaN
132,accommodates.norm,4,"14,945.00 ( 8.50%)","4,689.00 ( 7.70%)","7,185.00 ( 8.80%)","3,071.00 ( 8.90%)",NaN
133,accommodates.norm,0,"7,321.00 ( 4.10%)","2,581.00 ( 4.30%)","3,297.00 ( 4.00%)","1,443.00 ( 4.20%)",NaN

In [160]:
tab1[tab1['p_value']<0.05]

,Variables,Categories,Population,Category_0,Category_1,Category_2,p_value
1,week_num,Mean (SD),28.10 ( 15.80),26.40 ( 14.20),29.70 ( 17.10),27.20 ( 14.90),0.0
4,avg_price,Mean (SD),5.10 ( 0.70),5.10 ( 0.70),5.00 ( 0.70),5.10 ( 0.70),0.0
7,min_price,Mean (SD),5.00 ( 0.70),5.10 ( 0.70),5.00 ( 0.70),5.00 ( 0.70),0.0
10,max_price,Mean (SD),5.10 ( 0.70),5.10 ( 0.70),5.10 ( 0.80),5.20 ( 0.70),0.0
14,host_is_superhost,1,"65,588.00 ( 37.20%)","25,425.00 ( 42.00%)","21,474.00 ( 26.30%)","18,689.00 ( 54.40%)",0.0
16,host_identity_verified,0,"80,786.00 ( 45.80%)","31,518.00 ( 52.10%)","31,979.00 ( 39.20%)","17,289.00 ( 50.30%)",0.0
17,latitude,Mean (SD),37.80 ( 0.00),37.80 ( 0.00),37.80 ( 0.00),37.80 ( 0.00),0.0
20,longitude,Mean (SD),-122.40 ( 0.00),-122.40 ( 0.00),-122.40 ( 0.00),-122.40 ( 0.00),0.0
24,is_location_exact,0,"27,381.00 ( 15.50%)","11,655.00 ( 19.30%)","11,067.00 ( 13.60%)","4,659.00 ( 13.60%)",0.0
26,property_type,House,"51,108.00 ( 29.00%)","14,895.00 ( 24.60%)","25,189.00 ( 30.90%)","11,024.00 ( 32.10%)",0.0
33,room_type,2,"71,138.00 ( 40.30%)","19,205.00 ( 31.70%)","35,690.00 ( 43.70%)","16,243.00 ( 47.30%)",0.0
36,accommodates,Mean (SD),3.10 ( 2.00),3.20 ( 1.90),3.10 ( 2.10),3.20 ( 1.90),0.0
40,bathrooms,2,"37,109.00 ( 21.00%)","12,213.00 ( 20.20%)","18,321.00 ( 22.50%)","6,575.00 ( 19.10%)",0.0
43,bedrooms,2,"44,573.00 ( 25.30%)","17,492.00 ( 28.90%)","18,658.00 ( 22.90%)","8,423.00 ( 24.50%)",0.0
46,beds,2,"44,213.00 ( 25.10%)","15,045.00 ( 24.90%)","20,066.00 ( 24.60%)","9,102.00 ( 26.50%)",0.0
49,bed_type,2,809.00 ( 0.50%),181.00 ( 0.30%),503.00 ( 0.60%),125.00 ( 0.40%),0.0
54,security_deposit,3,"48,343.00 ( 27.40%)","13,740.00 ( 22.70%)","23,325.00 ( 28.60%)","11,278.00 ( 32.80%)",0.0
58,cleaning_fee,0,"45,453.00 ( 25.80%)","18,850.00 ( 31.20%)","19,113.00 ( 23.40%)","7,490.00 ( 21.80%)",0.0
63,guests_included,2,"42,973.00 ( 24.40%)","15,589.00 ( 25.80%)","17,433.00 ( 21.40%)","9,951.00 ( 29.00%)",0.0
67,extra_people,0,"67,653.00 ( 38.30%)","20,836.00 ( 34.40%)","31,801.00 ( 39.00%)","15,016.00 ( 43.70%)",0.0
71,minimum_nights,1,"52,612.00 ( 29.80%)","24,962.00 ( 41.30%)","23,238.00 ( 28.50%)","4,412.00 ( 12.80%)",0.0
75,maximum_nights,3,"61,422.00 ( 34.80%)","19,457.00 ( 32.20%)","25,175.00 ( 30.90%)","16,790.00 ( 48.90%)",0.0
80,number_of_reviews,2,"34,590.00 ( 19.60%)","13,948.00 ( 23.10%)","17,279.00 ( 21.20%)","3,363.00 ( 9.80%)",0.0
84,review_scores_accuracy,2,"35,397.00 ( 20.10%)","14,128.00 ( 23.30%)","17,815.00 ( 21.80%)","3,454.00 ( 10.10%)",0.0
88,review_scores_cleanliness,2,"35,404.00 ( 20.10%)","14,128.00 ( 23.30%)","17,822.00 ( 21.80%)","3,454.00 ( 10.10%)",0.0
92,review_scores_checkin,2,"35,434.00 ( 20.10%)","14,128.00 ( 23.30%)","17,849.00 ( 21.90%)","3,457.00 ( 10.10%)",0.0
96,review_scores_communication,2,"35,396.00 ( 20.10%)","14,128.00 ( 23.30%)","17,814.00 ( 21.80%)","3,454.00 ( 10.10%)",0.0
100,review_scores_location,2,"35,432.00 ( 20.10%)","14,128.00 ( 23.30%)","17,847.00 ( 21.90%)","3,457.00 ( 10.10%)",0.0
104,review_scores_value,1,"60,878.00 ( 34.50%)","17,438.00 ( 28.80%)","29,994.00 ( 36.80%)","13,446.00 ( 39.10%)",0.0
108,instant_bookable,1,"73,026.00 ( 41.40%)","30,122.00 ( 49.80%)","26,879.00 ( 32.90%)","16,025.00 ( 46.70%)",0.0
110,cancellation_policy,1,"57,159.00 ( 32.40%)","19,102.00 ( 31.60%)","23,837.00 ( 29.20%)","14,220.00 ( 41.40%)",0.0
116,require_guest_profile_picture,1,"8,678.00 ( 4.90%)","2,462.00 ( 4.10%)","4,789.00 ( 5.90%)","1,427.00 ( 4.20%)",0.0
118,require_guest_phone_verification,1,"10,867.00 ( 6.20%)","3,271.00 ( 5.40%)","5,754.00 ( 7.10%)","1,842.00 ( 5.40%)",0.0
120,calculated_host_listings_count,3,"51,779.00 ( 29.30%)","15,591.00 ( 25.80%)","24,783.00 ( 30.40%)","11,405.00 ( 33.20%)",0.0
125,host_seniority,Mean (SD),4.10 ( 2.50),4.60 ( 2.50),3.50 ( 2.30),4.60 ( 2.50),0.0
129,accommodates.norm,1,"34,682.00 ( 19.70%)","12,092.00 ( 20.00%)","15,424.00 ( 18.90%)","7,166.00 ( 20.90%)",0.0

In [161]:
vn1 = tab1.loc[tab1['p_value']<0.05,'Variables'].unique()
print(len(vn1))
vn1

36

array(['week_num', 'avg_price', 'min_price', 'max_price',
       'host_is_superhost', 'host_identity_verified', 'latitude',
       'longitude', 'is_location_exact', 'property_type', 'room_type',
       'accommodates', 'bathrooms', 'bedrooms', 'beds', 'bed_type',
       'security_deposit', 'cleaning_fee', 'guests_included',
       'extra_people', 'minimum_nights', 'maximum_nights',
       'number_of_reviews', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'instant_bookable', 'cancellation_policy',
       'require_guest_profile_picture',
       'require_guest_phone_verification',
       'calculated_host_listings_count', 'host_seniority',
       'accommodates.norm'], dtype=object)

We will add these variables to our variable selection table

In [162]:
varSel['Univarable'] = 0
varSel.loc[varSel['Variable'].isin(vn1), 'Univarable'] = 1
varSel

                            Variable  Univarable
0                           week_num           1
1                          avg_price           1
2                          min_price           1
3                          max_price           1
4                  host_is_superhost           1
5             host_identity_verified           1
6             neighbourhood_cleansed           0
7                            zipcode           0
8                           latitude           1
9                          longitude           1
10                 is_location_exact           1
11                     property_type           1
12                         room_type           1
13                      accommodates           1
14                         bathrooms           1
15                          bedrooms           1
16                              beds           1
17                          bed_type           1
18                  security_deposit           1
19                      cleaning_fee           1
20                   guests_included           1
21                      extra_people           1
22                    minimum_nights           1
23                    maximum_nights           1
24                 number_of_reviews           1
25            review_scores_accuracy           1
26         review_scores_cleanliness           1
27             review_scores_checkin           1
28       review_scores_communication           1
29            review_scores_location           1
30               review_scores_value           1
31                  instant_bookable           1
32               cancellation_policy           1
33     require_guest_profile_picture           1
34  require_guest_phone_verification           1
35    calculated_host_listings_count           1
36                 reviews_per_month           0
37                    host_seniority           1
38                      occupied_cat           0
39                 accommodates.norm           1

## Multivariable Analysis

In [199]:
### drop na
df = df.dropna()

In [200]:
df.head()

,week_num,avg_price,min_price,max_price,host_is_superhost,host_identity_verified,neighbourhood_cleansed,zipcode,latitude,longitude,...,review_scores_value,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month,host_seniority,occupied_cat,accommodates.norm
0,12,4.934474,4.934474,4.934474,1,0,16,8,37.76697,-122.42404,...,3,1,0,0,0,1,6,4,0,5
1,13,4.934474,4.934474,4.934474,1,0,16,8,37.76697,-122.42404,...,3,1,0,0,0,1,6,4,1,5
2,11,4.934474,4.934474,4.934474,1,0,16,8,37.76697,-122.42404,...,3,1,0,0,0,1,6,4,2,5
3,14,4.934474,4.934474,4.934474,1,0,16,8,37.76697,-122.42404,...,3,1,0,0,0,1,6,4,2,5
4,11,4.465908,4.465908,4.465908,0,1,1,14,37.73612,-122.42110,...,1,0,3,0,0,2,0,10,0,5

In [201]:
## remove unnecessary vars
X = df.drop(['occupied_cat'], axis=1)
X.head()

,week_num,avg_price,min_price,max_price,host_is_superhost,host_identity_verified,neighbourhood_cleansed,zipcode,latitude,longitude,...,review_scores_location,review_scores_value,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month,host_seniority,accommodates.norm
0,12,4.934474,4.934474,4.934474,1,0,16,8,37.76697,-122.42404,...,3,3,1,0,0,0,1,6,4,5
1,13,4.934474,4.934474,4.934474,1,0,16,8,37.76697,-122.42404,...,3,3,1,0,0,0,1,6,4,5
2,11,4.934474,4.934474,4.934474,1,0,16,8,37.76697,-122.42404,...,3,3,1,0,0,0,1,6,4,5
3,14,4.934474,4.934474,4.934474,1,0,16,8,37.76697,-122.42404,...,3,3,1,0,0,0,1,6,4,5
4,11,4.465908,4.465908,4.465908,0,1,1,14,37.73612,-122.42110,...,3,1,0,3,0,0,2,0,10,5

In [202]:
y = df.loc[:, 'occupied_cat']
print([X.shape,y.shape])

[(176451, 39), (176451,)]

In [203]:
varSel

                            Variable
0                           week_num
1                          avg_price
2                          min_price
3                          max_price
4                  host_is_superhost
5             host_identity_verified
6             neighbourhood_cleansed
7                            zipcode
8                           latitude
9                          longitude
10                 is_location_exact
11                     property_type
12                         room_type
13                      accommodates
14                         bathrooms
15                          bedrooms
16                              beds
17                          bed_type
18                  security_deposit
19                      cleaning_fee
20                   guests_included
21                      extra_people
22                    minimum_nights
23                    maximum_nights
24                 number_of_reviews
25            review_scores_accuracy
26         review_scores_cleanliness
27             review_scores_checkin
28       review_scores_communication
29            review_scores_location
30               review_scores_value
31                  instant_bookable
32               cancellation_policy
33     require_guest_profile_picture
34  require_guest_phone_verification
35    calculated_host_listings_count
36                 reviews_per_month
37                    host_seniority
38                 accommodates.norm

### Variable Selection using LASSO (L1 penalization)

In [204]:
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel

lassomod = Lasso(alpha=0.01).fit(X, y)

In [205]:
model = SelectFromModel(lassomod, prefit=True)
model.get_support()

array([ True, False,  True,  True, False, False,  True,  True, False,
       False,  True,  True,  True, False, False, False, False, False,
        True, False, False,  True,  True,  True,  True, False, False,
        True,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True])

In [206]:
len(model.get_support())
varSel.shape
X.shape

(176451, 39)

In [207]:
varSel['Lasso'] = model.get_support().astype('int64')
varSel

                            Variable  Lasso
0                           week_num      1
1                          avg_price      0
2                          min_price      1
3                          max_price      1
4                  host_is_superhost      0
5             host_identity_verified      0
6             neighbourhood_cleansed      1
7                            zipcode      1
8                           latitude      0
9                          longitude      0
10                 is_location_exact      1
11                     property_type      1
12                         room_type      1
13                      accommodates      0
14                         bathrooms      0
15                          bedrooms      0
16                              beds      0
17                          bed_type      0
18                  security_deposit      1
19                      cleaning_fee      0
20                   guests_included      0
21                      extra_people      1
22                    minimum_nights      1
23                    maximum_nights      1
24                 number_of_reviews      1
25            review_scores_accuracy      0
26         review_scores_cleanliness      0
27             review_scores_checkin      1
28       review_scores_communication      1
29            review_scores_location      0
30               review_scores_value      1
31                  instant_bookable      1
32               cancellation_policy      0
33     require_guest_profile_picture      0
34  require_guest_phone_verification      0
35    calculated_host_listings_count      1
36                 reviews_per_month      1
37                    host_seniority      1
38                 accommodates.norm      1

### Variable Selection using Random Forest

In [208]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

rfmod = RandomForestClassifier().fit(X, y)
#rfmod.feature_importances_

C:\Users\vladip\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [209]:
model = SelectFromModel(rfmod, prefit=True)
model.get_support()

array([ True,  True,  True,  True, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
        True,  True, False])

In [210]:
varSel['RandomForest'] = model.get_support().astype('int64')
varSel

                            Variable  Lasso  RandomForest
0                           week_num      1             1
1                          avg_price      0             1
2                          min_price      1             1
3                          max_price      1             1
4                  host_is_superhost      0             0
5             host_identity_verified      0             0
6             neighbourhood_cleansed      1             0
7                            zipcode      1             0
8                           latitude      0             1
9                          longitude      0             1
10                 is_location_exact      1             0
11                     property_type      1             0
12                         room_type      1             0
13                      accommodates      0             0
14                         bathrooms      0             0
15                          bedrooms      0             0
16                              beds      0             0
17                          bed_type      0             0
18                  security_deposit      1             0
19                      cleaning_fee      0             0
20                   guests_included      0             0
21                      extra_people      1             0
22                    minimum_nights      1             0
23                    maximum_nights      1             0
24                 number_of_reviews      1             0
25            review_scores_accuracy      0             0
26         review_scores_cleanliness      0             0
27             review_scores_checkin      1             0
28       review_scores_communication      1             0
29            review_scores_location      0             0
30               review_scores_value      1             0
31                  instant_bookable      1             0
32               cancellation_policy      0             1
33     require_guest_profile_picture      0             0
34  require_guest_phone_verification      0             0
35    calculated_host_listings_count      1             0
36                 reviews_per_month      1             1
37                    host_seniority      1             1
38                 accommodates.norm      1             0

### Variable Selection using Gradient Boosting classification

In [211]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.feature_selection import SelectFromModel

gbmod = GradientBoostingClassifier().fit(X, y)

In [212]:
model = SelectFromModel(gbmod, prefit=True)
model.get_support()

array([ True, False, False, False,  True,  True, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False, False, False, False,  True,  True, False, False,  True,
       False,  True, False])

In [213]:
varSel['GradientBoost'] = model.get_support().astype('int64')
varSel

                            Variable  Lasso  RandomForest  GradientBoost
0                           week_num      1             1              1
1                          avg_price      0             1              0
2                          min_price      1             1              0
3                          max_price      1             1              0
4                  host_is_superhost      0             0              1
5             host_identity_verified      0             0              1
6             neighbourhood_cleansed      1             0              0
7                            zipcode      1             0              0
8                           latitude      0             1              0
9                          longitude      0             1              0
10                 is_location_exact      1             0              0
11                     property_type      1             0              0
12                         room_type      1             0              1
13                      accommodates      0             0              0
14                         bathrooms      0             0              0
15                          bedrooms      0             0              0
16                              beds      0             0              0
17                          bed_type      0             0              0
18                  security_deposit      1             0              0
19                      cleaning_fee      0             0              0
20                   guests_included      0             0              0
21                      extra_people      1             0              0
22                    minimum_nights      1             0              1
23                    maximum_nights      1             0              0
24                 number_of_reviews      1             0              1
25            review_scores_accuracy      0             0              0
26         review_scores_cleanliness      0             0              0
27             review_scores_checkin      1             0              0
28       review_scores_communication      1             0              0
29            review_scores_location      0             0              0
30               review_scores_value      1             0              0
31                  instant_bookable      1             0              1
32               cancellation_policy      0             1              1
33     require_guest_profile_picture      0             0              0
34  require_guest_phone_verification      0             0              0
35    calculated_host_listings_count      1             0              1
36                 reviews_per_month      1             1              0
37                    host_seniority      1             1              1
38                 accommodates.norm      1             0              0

### Variable Selection using SVM classification

In [214]:
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel

svmmod = LinearSVC(C=0.01, penalty="l1",dual=False).fit(X, y)

C:\Users\vladip\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

In [215]:
model = SelectFromModel(svmmod, prefit=True)
model.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [216]:
varSel['SVM'] = model.get_support().astype('int64')
varSel

                            Variable  Lasso  RandomForest  GradientBoost  SVM
0                           week_num      1             1              1    1
1                          avg_price      0             1              0    1
2                          min_price      1             1              0    1
3                          max_price      1             1              0    1
4                  host_is_superhost      0             0              1    1
5             host_identity_verified      0             0              1    1
6             neighbourhood_cleansed      1             0              0    1
7                            zipcode      1             0              0    1
8                           latitude      0             1              0    1
9                          longitude      0             1              0    1
10                 is_location_exact      1             0              0    1
11                     property_type      1             0              0    1
12                         room_type      1             0              1    1
13                      accommodates      0             0              0    1
14                         bathrooms      0             0              0    1
15                          bedrooms      0             0              0    1
16                              beds      0             0              0    1
17                          bed_type      0             0              0    1
18                  security_deposit      1             0              0    1
19                      cleaning_fee      0             0              0    1
20                   guests_included      0             0              0    1
21                      extra_people      1             0              0    1
22                    minimum_nights      1             0              1    1
23                    maximum_nights      1             0              0    1
24                 number_of_reviews      1             0              1    1
25            review_scores_accuracy      0             0              0    1
26         review_scores_cleanliness      0             0              0    1
27             review_scores_checkin      1             0              0    1
28       review_scores_communication      1             0              0    1
29            review_scores_location      0             0              0    1
30               review_scores_value      1             0              0    1
31                  instant_bookable      1             0              1    1
32               cancellation_policy      0             1              1    1
33     require_guest_profile_picture      0             0              0    1
34  require_guest_phone_verification      0             0              0    1
35    calculated_host_listings_count      1             0              1    1
36                 reviews_per_month      1             1              0    1
37                    host_seniority      1             1              1    1
38                 accommodates.norm      1             0              0    1

### Summarization and Selection of Variables

In [217]:
varSel['Sum'] =  np.sum(varSel,axis=1)
varSel

,Variable,Lasso,RandomForest,GradientBoost,SVM,Sum
0,week_num,1,1,1,1,4
1,avg_price,0,1,0,1,2
2,min_price,1,1,0,1,3
3,max_price,1,1,0,1,3
4,host_is_superhost,0,0,1,1,2
5,host_identity_verified,0,0,1,1,2
6,neighbourhood_cleansed,1,0,0,1,2
7,zipcode,1,0,0,1,2
8,latitude,0,1,0,1,2
9,longitude,0,1,0,1,2
10,is_location_exact,1,0,0,1,2
11,property_type,1,0,0,1,2
12,room_type,1,0,1,1,3
13,accommodates,0,0,0,1,1
14,bathrooms,0,0,0,1,1
15,bedrooms,0,0,0,1,1
16,beds,0,0,0,1,1
17,bed_type,0,0,0,1,1
18,security_deposit,1,0,0,1,2
19,cleaning_fee,0,0,0,1,1
20,guests_included,0,0,0,1,1
21,extra_people,1,0,0,1,2
22,minimum_nights,1,0,1,1,3
23,maximum_nights,1,0,0,1,2
24,number_of_reviews,1,0,1,1,3
25,review_scores_accuracy,0,0,0,1,1
26,review_scores_cleanliness,0,0,0,1,1
27,review_scores_checkin,1,0,0,1,2
28,review_scores_communication,1,0,0,1,2
29,review_scores_location,0,0,0,1,1
30,review_scores_value,1,0,0,1,2
31,instant_bookable,1,0,1,1,3
32,cancellation_policy,0,1,1,1,3
33,require_guest_profile_picture,0,0,0,1,1
34,require_guest_phone_verification,0,0,0,1,1
35,calculated_host_listings_count,1,0,1,1,3
36,reviews_per_month,1,1,0,1,3
37,host_seniority,1,1,1,1,4
38,accommodates.norm,1,0,0,1,2

In [218]:
varSel.groupby('Sum')['Variable'].count()

Sum
1    12
2    16
3     9
4     2
Name: Variable, dtype: int64

We can now decide a threshold for selecting our variables!

In [223]:
varSel[varSel.Sum > 1]

,Variable,Lasso,RandomForest,GradientBoost,SVM,Sum
0,week_num,1,1,1,1,4
1,avg_price,0,1,0,1,2
2,min_price,1,1,0,1,3
3,max_price,1,1,0,1,3
4,host_is_superhost,0,0,1,1,2
5,host_identity_verified,0,0,1,1,2
6,neighbourhood_cleansed,1,0,0,1,2
7,zipcode,1,0,0,1,2
8,latitude,0,1,0,1,2
9,longitude,0,1,0,1,2
10,is_location_exact,1,0,0,1,2
11,property_type,1,0,0,1,2
12,room_type,1,0,1,1,3
18,security_deposit,1,0,0,1,2
21,extra_people,1,0,0,1,2
22,minimum_nights,1,0,1,1,3
23,maximum_nights,1,0,0,1,2
24,number_of_reviews,1,0,1,1,3
27,review_scores_checkin,1,0,0,1,2
28,review_scores_communication,1,0,0,1,2
30,review_scores_value,1,0,0,1,2
31,instant_bookable,1,0,1,1,3
32,cancellation_policy,0,1,1,1,3
35,calculated_host_listings_count,1,0,1,1,3
36,reviews_per_month,1,1,0,1,3
37,host_seniority,1,1,1,1,4
38,accommodates.norm,1,0,0,1,2