# Feature Selection

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import os
import sklearn as sklearn

In [2]:
path = os.getcwd()

print(path)
os.chdir('C:\\bb\\airbnb')

df = pd.read_csv(".\\data\\FF_train_clean_enriched2.csv")
df.head()

C:\bb\airbnb

,week_num_1,week_num_10,week_num_11,week_num_12,week_num_13,week_num_14,week_num_15,week_num_16,week_num_17,week_num_18,...,amenities_Washer,amenities_Wifi,amenities_Carbonmonoxidedetector,amenities_Hangers,amenities_TV,amenities_Shampoo,amenities_Kitchen,amenities_Smokedetector,amenities_Essentials,amenities_Heating
0,0,0,0,1,0,0,0,0,0,0,...,0,1,1,1,1,1,0,1,1,1
1,0,0,0,0,1,0,0,0,0,0,...,0,1,1,1,1,1,0,1,1,1
2,0,0,1,0,0,0,0,0,0,0,...,0,1,1,1,1,1,0,1,1,1
3,0,0,0,0,0,1,0,0,0,0,...,0,1,1,1,1,1,0,1,1,1
4,0,0,1,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,1,1

In [3]:
df['bathrooms'] = df['bathrooms'].astype('category')
df['bedrooms'] = df['bedrooms'].astype('category')
df['beds'] = df['beds'].astype('category')
df['security_deposit'] = df['security_deposit'].astype('category')
df['cleaning_fee'] = df['cleaning_fee'].astype('category')
df['guests_included'] = df['guests_included'].astype('category')
df['extra_people'] = df['extra_people'].astype('category')
df['minimum_nights'] = df['minimum_nights'].astype('category')
df['maximum_nights'] = df['maximum_nights'].astype('category')
df['number_of_reviews'] = df['number_of_reviews'].astype('category')
df['cancellation_policy'] = df['cancellation_policy'].astype('category')
df['calculated_host_listings_count'] = df['calculated_host_listings_count'].astype('category')
df['accommodates.norm'] = df['accommodates.norm'].astype('category')

df['occupied_cat'] = df['occupied_cat'].astype('category').cat.codes

In [4]:
varSel = pd.DataFrame({'Variable': df.columns[~df.columns.isin(['occupied_cat'])]})
varSel.head()

      Variable
0   week_num_1
1  week_num_10
2  week_num_11
3  week_num_12
4  week_num_13

## Univariable Analysis

In [5]:
import pyMechkar as pm

In [6]:
from pyMechkar import analysis as apm

In [7]:
df.columns

Index(['week_num_1', 'week_num_10', 'week_num_11', 'week_num_12',
       'week_num_13', 'week_num_14', 'week_num_15', 'week_num_16',
       'week_num_17', 'week_num_18',
       ...
       'amenities_Washer', 'amenities_Wifi',
       'amenities_Carbonmonoxidedetector', 'amenities_Hangers', 'amenities_TV',
       'amenities_Shampoo', 'amenities_Kitchen', 'amenities_Smokedetector',
       'amenities_Essentials', 'amenities_Heating'],
      dtype='object', length=276)

In [8]:
df.head()

,week_num_1,week_num_10,week_num_11,week_num_12,week_num_13,week_num_14,week_num_15,week_num_16,week_num_17,week_num_18,...,amenities_Washer,amenities_Wifi,amenities_Carbonmonoxidedetector,amenities_Hangers,amenities_TV,amenities_Shampoo,amenities_Kitchen,amenities_Smokedetector,amenities_Essentials,amenities_Heating
0,0,0,0,1,0,0,0,0,0,0,...,0,1,1,1,1,1,0,1,1,1
1,0,0,0,0,1,0,0,0,0,0,...,0,1,1,1,1,1,0,1,1,1
2,0,0,1,0,0,0,0,0,0,0,...,0,1,1,1,1,1,0,1,1,1
3,0,0,0,0,0,1,0,0,0,0,...,0,1,1,1,1,1,0,1,1,1
4,0,0,1,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,1,1

In [9]:
tab1 = apm.Table1(x=list(df.columns.values), 
                  y="occupied_cat", data=df)

Begining analysis...
Factorizing... please wait
***********************************************************************************************************************************************************************************************************************************************************************************
[]
[************************************************************************************************************************************************************************************************************************************************************************************
[************************************************************************************************************************************************************************************************************************************************************************************
[************************************************************************************************************************************************************************************************************************************************************************************
['Unable to calcualte the Fisher exact test for variables week_num_2 and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables neighbourhood_cleansed_Treasure_Island_YBI and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables zipcode_00901 and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables zipcode_60614 and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables zipcode_94005 and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables zipcode_94030 and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables zipcode_94128 and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables zipcode_94130 and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables zipcode_94306 and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables zipcode_94510 and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables zipcode_94611 and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables zipcode_94965 and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables zipcode_95014 and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables zipcode_95202 and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Barn and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Bed___Breakfast and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Bus and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Camper_RV and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Casa_particular and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Cave and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Chalet and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Dome_house and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Dorm and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Entire_Floor and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Floor and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Hut and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_In_law and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Lighthouse and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Pension__Korea_ and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Tent and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Treehouse and occupied_cat... The p-value may be incorrect', 'Unable to calcualte the Fisher exact test for variables property_type_Vacation_home and occupied_cat... The p-value may be incorrect']
------ Finished in 657.2202906608582econds -----

In [10]:
tab1

,Variables,Categories,Population,Category_0,Category_1,Category_2,p_value
0,Individuals,n,176451,60510,81594,34347,NaN
1,week_num_1,0,"172,204.00 ( 97.60%)","59,844.00 ( 98.90%)","78,573.00 ( 96.30%)","33,787.00 ( 98.40%)",NaN
2,week_num_1,1,"4,247.00 ( 2.40%)",666.00 ( 1.10%),"3,021.00 ( 3.70%)",560.00 ( 1.60%),0.000
3,week_num_10,0,"173,614.00 ( 98.40%)","59,424.00 ( 98.20%)","80,793.00 ( 99.00%)","33,397.00 ( 97.20%)",NaN
4,week_num_10,1,"2,837.00 ( 1.60%)","1,086.00 ( 1.80%)",801.00 ( 1.00%),950.00 ( 2.80%),0.000
5,week_num_11,0,"173,345.00 ( 98.20%)","59,220.00 ( 97.90%)","80,451.00 ( 98.60%)","33,674.00 ( 98.00%)",NaN
6,week_num_11,1,"3,106.00 ( 1.80%)","1,290.00 ( 2.10%)","1,143.00 ( 1.40%)",673.00 ( 2.00%),0.000
7,week_num_12,0,"173,272.00 ( 98.20%)","58,998.00 ( 97.50%)","80,590.00 ( 98.80%)","33,684.00 ( 98.10%)",NaN
8,week_num_12,1,"3,179.00 ( 1.80%)","1,512.00 ( 2.50%)","1,004.00 ( 1.20%)",663.00 ( 1.90%),0.000
9,week_num_13,0,"173,074.00 ( 98.10%)","59,333.00 ( 98.10%)","79,888.00 ( 97.90%)","33,853.00 ( 98.60%)",NaN
10,week_num_13,1,"3,377.00 ( 1.90%)","1,177.00 ( 1.90%)","1,706.00 ( 2.10%)",494.00 ( 1.40%),0.000
11,week_num_14,0,"173,932.00 ( 98.60%)","59,518.00 ( 98.40%)","81,001.00 ( 99.30%)","33,413.00 ( 97.30%)",NaN
12,week_num_14,1,"2,519.00 ( 1.40%)",992.00 ( 1.60%),593.00 ( 0.70%),934.00 ( 2.70%),0.000
13,week_num_15,0,"173,417.00 ( 98.30%)","59,090.00 ( 97.70%)","80,714.00 ( 98.90%)","33,613.00 ( 97.90%)",NaN
14,week_num_15,1,"3,034.00 ( 1.70%)","1,420.00 ( 2.30%)",880.00 ( 1.10%),734.00 ( 2.10%),0.000
15,week_num_16,0,"172,743.00 ( 97.90%)","59,285.00 ( 98.00%)","79,804.00 ( 97.80%)","33,654.00 ( 98.00%)",NaN
16,week_num_16,1,"3,708.00 ( 2.10%)","1,225.00 ( 2.00%)","1,790.00 ( 2.20%)",693.00 ( 2.00%),0.043
17,week_num_17,0,"172,352.00 ( 97.70%)","59,395.00 ( 98.20%)","79,210.00 ( 97.10%)","33,747.00 ( 98.30%)",NaN
18,week_num_17,1,"4,099.00 ( 2.30%)","1,115.00 ( 1.80%)","2,384.00 ( 2.90%)",600.00 ( 1.70%),0.000
19,week_num_18,0,"172,826.00 ( 97.90%)","59,511.00 ( 98.30%)","79,669.00 ( 97.60%)","33,646.00 ( 98.00%)",NaN
20,week_num_18,1,"3,625.00 ( 2.10%)",999.00 ( 1.70%),"1,925.00 ( 2.40%)",701.00 ( 2.00%),0.000
21,week_num_19,0,"173,504.00 ( 98.30%)","59,213.00 ( 97.90%)","80,626.00 ( 98.80%)","33,665.00 ( 98.00%)",NaN
22,week_num_19,1,"2,947.00 ( 1.70%)","1,297.00 ( 2.10%)",968.00 ( 1.20%),682.00 ( 2.00%),0.000
23,week_num_2,0,"175,438.00 ( 99.40%)","60,510.00 ( 100.00%)","80,957.00 ( 99.20%)","33,971.00 ( 98.90%)",NaN
24,week_num_2,1,"1,013.00 ( 0.60%)",0.00 ( 0.00%),637.00 ( 0.80%),376.00 ( 1.10%),0.000
25,week_num_20,0,"173,352.00 ( 98.20%)","59,200.00 ( 97.80%)","80,475.00 ( 98.60%)","33,677.00 ( 98.00%)",NaN
26,week_num_20,1,"3,099.00 ( 1.80%)","1,310.00 ( 2.20%)","1,119.00 ( 1.40%)",670.00 ( 2.00%),0.000
27,week_num_21,0,"173,190.00 ( 98.20%)","59,222.00 ( 97.90%)","80,253.00 ( 98.40%)","33,715.00 ( 98.20%)",NaN
28,week_num_21,1,"3,261.00 ( 1.80%)","1,288.00 ( 2.10%)","1,341.00 ( 1.60%)",632.00 ( 1.80%),0.000
29,week_num_22,0,"173,148.00 ( 98.10%)","59,436.00 ( 98.20%)","80,036.00 ( 98.10%)","33,676.00 ( 98.00%)",NaN
...,...,...,...,...,...,...,...
564,amenities_Laptopfriendlyworkspace,0,"93,826.00 ( 53.20%)","29,065.00 ( 48.00%)","49,141.00 ( 60.20%)","15,620.00 ( 45.50%)",NaN
565,amenities_Laptopfriendlyworkspace,1,"82,625.00 ( 46.80%)","31,445.00 ( 52.00%)","32,453.00 ( 39.80%)","18,727.00 ( 54.50%)",0.000
566,amenities_Fireextinguisher,1,"107,982.00 ( 61.20%)","41,583.00 ( 68.70%)","40,919.00 ( 50.10%)","25,480.00 ( 74.20%)",NaN
567,amenities_Fireextinguisher,0,"68,469.00 ( 38.80%)","18,927.00 ( 31.30%)","40,675.00 ( 49.90%)","8,867.00 ( 25.80%)",0.000
568,amenities_Iron,1,"112,192.00 ( 63.60%)","44,008.00 ( 72.70%)","43,965.00 ( 53.90%)","24,219.00 ( 70.50%)",NaN
569,amenities_Iron,0,"64,259.00 ( 36.40%)","16,502.00 ( 27.30%)","37,629.00 ( 46.10%)","10,128.00 ( 29.50%)",0.000
570,amenities_Hairdryer,1,"116,925.00 ( 66.30%)","46,727.00 ( 77.20%)","43,276.00 ( 53.00%)","26,922.00 ( 78.40%)",NaN
571,amenities_Hairdryer,0,"59,526.00 ( 33.70%)","13,783.00 ( 22.80%)","38,318.00 ( 47.00%)","7,425.00 ( 21.60%)",0.000
572,amenities_Dryer,1,"121,801.00 ( 69.00%)","44,856.00 ( 74.10%)","55,807.00 ( 68.40%)","21,138.00 ( 61.50%)",NaN
573,amenities_Dryer,0,"54,650.00 ( 31.00%)","15,654.00 ( 25.90%)","25,787.00 ( 31.60%)","13,209.00 ( 38.50%)",0.000
574,amenities_Washer,1,"120,696.00 ( 68.40%)","45,075.00 ( 74.50%)","54,376.00 ( 66.60%)","21,245.00 ( 61.90%)",NaN
575,amenities_Washer,0,"55,755.00 ( 31.60%)","15,435.00 ( 25.50%)","27,218.00 ( 33.40%)","13,102.00 ( 38.10%)",0.000
576,amenities_Wifi,1,"130,540.00 ( 74.00%)","58,970.00 ( 97.50%)","37,451.00 ( 45.90%)","34,119.00 ( 99.30%)",NaN
577,amenities_Wifi,0,"45,911.00 ( 26.00%)","1,540.00 ( 2.50%)","44,143.00 ( 54.10%)",228.00 ( 0.70%),0.000
578,amenities_Carbonmonoxidedetector,1,"131,907.00 ( 74.80%)","52,106.00 ( 86.10%)","49,969.00 ( 61.20%)","29,832.00 ( 86.90%)",NaN
579,amenities_Carbonmonoxidedetector,0,"44,544.00 ( 25.20%)","8,404.00 ( 13.90%)","31,625.00 ( 38.80%)","4,515.00 ( 13.10%)",0.000
580,amenities_Hangers,1,"131,913.00 ( 74.80%)","49,933.00 ( 82.50%)","53,503.00 ( 65.60%)","28,477.00 ( 82.90%)",NaN
581,amenities_Hangers,0,"44,538.00 ( 25.20%)","10,577.00 ( 17.50%)","28,091.00 ( 34.40%)","5,870.00 ( 17.10%)",0.000
582,amenities_TV,1,"138,277.00 ( 78.40%)","50,604.00 ( 83.60%)","60,644.00 ( 74.30%)","27,029.00 ( 78.70%)",NaN
583,amenities_TV,0,"38,174.00 ( 21.60%)","9,906.00 ( 16.40%)","20,950.00 ( 25.70%)","7,318.00 ( 21.30%)",0.000
584,amenities_Shampoo,1,"140,700.00 ( 79.70%)","50,048.00 ( 82.70%)","60,360.00 ( 74.00%)","30,292.00 ( 88.20%)",NaN
585,amenities_Shampoo,0,"35,751.00 ( 20.30%)","10,462.00 ( 17.30%)","21,234.00 ( 26.00%)","4,055.00 ( 11.80%)",0.000
586,amenities_Kitchen,1,"142,144.00 ( 80.60%)","49,595.00 ( 82.00%)","67,451.00 ( 82.70%)","25,098.00 ( 73.10%)",NaN
587,amenities_Kitchen,0,"34,307.00 ( 19.40%)","10,915.00 ( 18.00%)","14,143.00 ( 17.30%)","9,249.00 ( 26.90%)",0.000
588,amenities_Smokedetector,1,"148,688.00 ( 84.30%)","57,723.00 ( 95.40%)","58,281.00 ( 71.40%)","32,684.00 ( 95.20%)",NaN
589,amenities_Smokedetector,0,"27,763.00 ( 15.70%)","2,787.00 ( 4.60%)","23,313.00 ( 28.60%)","1,663.00 ( 4.80%)",0.000
590,amenities_Essentials,1,"160,667.00 ( 91.10%)","57,024.00 ( 94.20%)","70,944.00 ( 86.90%)","32,699.00 ( 95.20%)",NaN
591,amenities_Essentials,0,"15,784.00 ( 8.90%)","3,486.00 ( 5.80%)","10,650.00 ( 13.10%)","1,648.00 ( 4.80%)",0.000
592,amenities_Heating,1,"164,800.00 ( 93.40%)","57,370.00 ( 94.80%)","74,829.00 ( 91.70%)","32,601.00 ( 94.90%)",NaN
593,amenities_Heating,0,"11,651.00 ( 6.60%)","3,140.00 ( 5.20%)","6,765.00 ( 8.30%)","1,746.00 ( 5.10%)",0.000

In [11]:
tab1[tab1['p_value']<0.05]

,Variables,Categories,Population,Category_0,Category_1,Category_2,p_value
2,week_num_1,1,"4,247.00 ( 2.40%)",666.00 ( 1.10%),"3,021.00 ( 3.70%)",560.00 ( 1.60%),0.000
4,week_num_10,1,"2,837.00 ( 1.60%)","1,086.00 ( 1.80%)",801.00 ( 1.00%),950.00 ( 2.80%),0.000
6,week_num_11,1,"3,106.00 ( 1.80%)","1,290.00 ( 2.10%)","1,143.00 ( 1.40%)",673.00 ( 2.00%),0.000
8,week_num_12,1,"3,179.00 ( 1.80%)","1,512.00 ( 2.50%)","1,004.00 ( 1.20%)",663.00 ( 1.90%),0.000
10,week_num_13,1,"3,377.00 ( 1.90%)","1,177.00 ( 1.90%)","1,706.00 ( 2.10%)",494.00 ( 1.40%),0.000
12,week_num_14,1,"2,519.00 ( 1.40%)",992.00 ( 1.60%),593.00 ( 0.70%),934.00 ( 2.70%),0.000
14,week_num_15,1,"3,034.00 ( 1.70%)","1,420.00 ( 2.30%)",880.00 ( 1.10%),734.00 ( 2.10%),0.000
16,week_num_16,1,"3,708.00 ( 2.10%)","1,225.00 ( 2.00%)","1,790.00 ( 2.20%)",693.00 ( 2.00%),0.043
18,week_num_17,1,"4,099.00 ( 2.30%)","1,115.00 ( 1.80%)","2,384.00 ( 2.90%)",600.00 ( 1.70%),0.000
20,week_num_18,1,"3,625.00 ( 2.10%)",999.00 ( 1.70%),"1,925.00 ( 2.40%)",701.00 ( 2.00%),0.000
22,week_num_19,1,"2,947.00 ( 1.70%)","1,297.00 ( 2.10%)",968.00 ( 1.20%),682.00 ( 2.00%),0.000
24,week_num_2,1,"1,013.00 ( 0.60%)",0.00 ( 0.00%),637.00 ( 0.80%),376.00 ( 1.10%),0.000
26,week_num_20,1,"3,099.00 ( 1.80%)","1,310.00 ( 2.20%)","1,119.00 ( 1.40%)",670.00 ( 2.00%),0.000
28,week_num_21,1,"3,261.00 ( 1.80%)","1,288.00 ( 2.10%)","1,341.00 ( 1.60%)",632.00 ( 1.80%),0.000
32,week_num_23,1,"3,164.00 ( 1.80%)","1,620.00 ( 2.70%)",940.00 ( 1.20%),604.00 ( 1.80%),0.000
34,week_num_24,1,"2,978.00 ( 1.70%)","1,476.00 ( 2.40%)",855.00 ( 1.00%),647.00 ( 1.90%),0.000
36,week_num_25,1,"3,046.00 ( 1.70%)","1,424.00 ( 2.40%)","1,000.00 ( 1.20%)",622.00 ( 1.80%),0.000
38,week_num_26,1,"3,303.00 ( 1.90%)","1,389.00 ( 2.30%)","1,321.00 ( 1.60%)",593.00 ( 1.70%),0.000
40,week_num_27,1,"2,818.00 ( 1.60%)","1,150.00 ( 1.90%)","1,134.00 ( 1.40%)",534.00 ( 1.60%),0.000
42,week_num_28,1,"2,784.00 ( 1.60%)","1,162.00 ( 1.90%)",731.00 ( 0.90%),891.00 ( 2.60%),0.000
44,week_num_29,1,"2,915.00 ( 1.70%)","1,430.00 ( 2.40%)",893.00 ( 1.10%),592.00 ( 1.70%),0.000
46,week_num_3,1,"3,109.00 ( 1.80%)","1,226.00 ( 2.00%)","1,304.00 ( 1.60%)",579.00 ( 1.70%),0.000
48,week_num_30,1,"3,167.00 ( 1.80%)","1,344.00 ( 2.20%)","1,249.00 ( 1.50%)",574.00 ( 1.70%),0.000
50,week_num_31,1,"2,954.00 ( 1.70%)","1,224.00 ( 2.00%)","1,124.00 ( 1.40%)",606.00 ( 1.80%),0.000
52,week_num_32,1,"2,396.00 ( 1.40%)","1,285.00 ( 2.10%)",300.00 ( 0.40%),811.00 ( 2.40%),0.000
54,week_num_33,1,"3,015.00 ( 1.70%)","1,447.00 ( 2.40%)",881.00 ( 1.10%),687.00 ( 2.00%),0.000
56,week_num_34,1,"3,526.00 ( 2.00%)","1,299.00 ( 2.10%)","1,571.00 ( 1.90%)",656.00 ( 1.90%),0.006
58,week_num_35,1,"3,528.00 ( 2.00%)","1,126.00 ( 1.90%)","1,696.00 ( 2.10%)",706.00 ( 2.10%),0.011
60,week_num_36,1,"2,982.00 ( 1.70%)","1,145.00 ( 1.90%)","1,227.00 ( 1.50%)",610.00 ( 1.80%),0.000
62,week_num_37,1,"2,988.00 ( 1.70%)","1,108.00 ( 1.80%)",927.00 ( 1.10%),953.00 ( 2.80%),0.000
...,...,...,...,...,...,...,...
525,reviews_per_month_8,1,"2,082.00 ( 1.20%)",664.00 ( 1.10%),527.00 ( 0.60%),891.00 ( 2.60%),0.000
527,reviews_per_month_9,1,"1,050.00 ( 0.60%)",357.00 ( 0.60%),239.00 ( 0.30%),454.00 ( 1.30%),0.000
529,reviews_per_month_Missing,1,"35,185.00 ( 19.90%)","14,154.00 ( 23.40%)","17,449.00 ( 21.40%)","3,582.00 ( 10.40%)",0.000
530,host_seniority,Mean (SD),4.10 ( 2.50),4.60 ( 2.50),3.50 ( 2.30),4.60 ( 2.50),0.000
534,accommodates.norm,4,"34,682.00 ( 19.70%)","12,092.00 ( 20.00%)","15,424.00 ( 18.90%)","7,166.00 ( 20.90%)",0.000
539,host_about_len,Mean (SD),154.80 ( 109.10),163.20 ( 108.40),146.00 ( 109.60),161.00 ( 107.70),0.000
542,description_len,Mean (SD),250.30 ( 25.90),250.30 ( 26.50),249.30 ( 28.00),252.70 ( 18.50),0.000
545,summary_len,Mean (SD),229.80 ( 55.40),233.20 ( 51.30),224.00 ( 60.60),237.50 ( 47.40),0.000
548,total_amenities,Mean (SD),17.80 ( 3.80),18.90 ( 3.40),16.60 ( 4.10),18.60 ( 2.60),0.000
551,price_per_person,Mean (SD),2.10 ( 1.00),2.00 ( 0.90),2.10 ( 1.00),2.00 ( 0.90),0.000
555,amenities_Freestreetparking,1,"56,172.00 ( 31.80%)","23,981.00 ( 39.60%)","14,299.00 ( 17.50%)","17,892.00 ( 52.10%)",0.000
557,amenities_Familykidfriendly,1,"58,984.00 ( 33.40%)","21,894.00 ( 36.20%)","24,884.00 ( 30.50%)","12,206.00 ( 35.50%)",0.000
559,amenities_CableTV,1,"70,451.00 ( 39.90%)","26,768.00 ( 44.20%)","31,297.00 ( 38.40%)","12,386.00 ( 36.10%)",0.000
561,amenities_Internet,0,"87,533.00 ( 49.60%)","39,670.00 ( 65.60%)","25,190.00 ( 30.90%)","22,673.00 ( 66.00%)",0.000
563,amenities_Firstaidkit,1,"78,504.00 ( 44.50%)","27,621.00 ( 45.60%)","30,697.00 ( 37.60%)","20,186.00 ( 58.80%)",0.000
565,amenities_Laptopfriendlyworkspace,1,"82,625.00 ( 46.80%)","31,445.00 ( 52.00%)","32,453.00 ( 39.80%)","18,727.00 ( 54.50%)",0.000
567,amenities_Fireextinguisher,0,"68,469.00 ( 38.80%)","18,927.00 ( 31.30%)","40,675.00 ( 49.90%)","8,867.00 ( 25.80%)",0.000
569,amenities_Iron,0,"64,259.00 ( 36.40%)","16,502.00 ( 27.30%)","37,629.00 ( 46.10%)","10,128.00 ( 29.50%)",0.000
571,amenities_Hairdryer,0,"59,526.00 ( 33.70%)","13,783.00 ( 22.80%)","38,318.00 ( 47.00%)","7,425.00 ( 21.60%)",0.000
573,amenities_Dryer,0,"54,650.00 ( 31.00%)","15,654.00 ( 25.90%)","25,787.00 ( 31.60%)","13,209.00 ( 38.50%)",0.000
575,amenities_Washer,0,"55,755.00 ( 31.60%)","15,435.00 ( 25.50%)","27,218.00 ( 33.40%)","13,102.00 ( 38.10%)",0.000
577,amenities_Wifi,0,"45,911.00 ( 26.00%)","1,540.00 ( 2.50%)","44,143.00 ( 54.10%)",228.00 ( 0.70%),0.000
579,amenities_Carbonmonoxidedetector,0,"44,544.00 ( 25.20%)","8,404.00 ( 13.90%)","31,625.00 ( 38.80%)","4,515.00 ( 13.10%)",0.000
581,amenities_Hangers,0,"44,538.00 ( 25.20%)","10,577.00 ( 17.50%)","28,091.00 ( 34.40%)","5,870.00 ( 17.10%)",0.000
583,amenities_TV,0,"38,174.00 ( 21.60%)","9,906.00 ( 16.40%)","20,950.00 ( 25.70%)","7,318.00 ( 21.30%)",0.000
585,amenities_Shampoo,0,"35,751.00 ( 20.30%)","10,462.00 ( 17.30%)","21,234.00 ( 26.00%)","4,055.00 ( 11.80%)",0.000
587,amenities_Kitchen,0,"34,307.00 ( 19.40%)","10,915.00 ( 18.00%)","14,143.00 ( 17.30%)","9,249.00 ( 26.90%)",0.000
589,amenities_Smokedetector,0,"27,763.00 ( 15.70%)","2,787.00 ( 4.60%)","23,313.00 ( 28.60%)","1,663.00 ( 4.80%)",0.000
591,amenities_Essentials,0,"15,784.00 ( 8.90%)","3,486.00 ( 5.80%)","10,650.00 ( 13.10%)","1,648.00 ( 4.80%)",0.000
593,amenities_Heating,0,"11,651.00 ( 6.60%)","3,140.00 ( 5.20%)","6,765.00 ( 8.30%)","1,746.00 ( 5.10%)",0.000

In [12]:
vn1 = tab1.loc[tab1['p_value']<0.05,'Variables'].unique()
print(len(vn1))
vn1

250

array(['week_num_1', 'week_num_10', 'week_num_11', 'week_num_12',
       'week_num_13', 'week_num_14', 'week_num_15', 'week_num_16',
       'week_num_17', 'week_num_18', 'week_num_19', 'week_num_2',
       'week_num_20', 'week_num_21', 'week_num_23', 'week_num_24',
       'week_num_25', 'week_num_26', 'week_num_27', 'week_num_28',
       'week_num_29', 'week_num_3', 'week_num_30', 'week_num_31',
       'week_num_32', 'week_num_33', 'week_num_34', 'week_num_35',
       'week_num_36', 'week_num_37', 'week_num_38', 'week_num_39',
       'week_num_4', 'week_num_40', 'week_num_41', 'week_num_42',
       'week_num_43', 'week_num_44', 'week_num_45', 'week_num_46',
       'week_num_47', 'week_num_48', 'week_num_49', 'week_num_5',
       'week_num_50', 'week_num_51', 'week_num_52', 'week_num_53',
       'week_num_6', 'week_num_7', 'week_num_8', 'week_num_9',
       'avg_price', 'min_price', 'max_price', 'host_is_superhost_f',
       'host_is_superhost_t', 'host_identity_verified_f',
       'host_identity_verified_t', 'neighbourhood_cleansed_Bayview',
       'neighbourhood_cleansed_Bernal_Heights',
       'neighbourhood_cleansed_Castro_Upper_Market',
       'neighbourhood_cleansed_Chinatown',
       'neighbourhood_cleansed_Crocker_Amazon',
       'neighbourhood_cleansed_Diamond_Heights',
       'neighbourhood_cleansed_Downtown_Civic_Center',
       'neighbourhood_cleansed_Excelsior',
       'neighbourhood_cleansed_Financial_District',
       'neighbourhood_cleansed_Golden_Gate_Park',
       'neighbourhood_cleansed_Haight_Ashbury',
       'neighbourhood_cleansed_Inner_Richmond',
       'neighbourhood_cleansed_Inner_Sunset',
       'neighbourhood_cleansed_Lakeshore',
       'neighbourhood_cleansed_Marina', 'neighbourhood_cleansed_Mission',
       'neighbourhood_cleansed_Nob_Hill',
       'neighbourhood_cleansed_Noe_Valley',
       'neighbourhood_cleansed_North_Beach',
       'neighbourhood_cleansed_Ocean_View',
       'neighbourhood_cleansed_Outer_Mission',
       'neighbourhood_cleansed_Outer_Richmond',
       'neighbourhood_cleansed_Outer_Sunset',
       'neighbourhood_cleansed_Pacific_Heights',
       'neighbourhood_cleansed_Parkside',
       'neighbourhood_cleansed_Potrero_Hill',
       'neighbourhood_cleansed_Presidio_Heights',
       'neighbourhood_cleansed_Russian_Hill',
       'neighbourhood_cleansed_Seacliff',
       'neighbourhood_cleansed_South_of_Market',
       'neighbourhood_cleansed_Treasure_Island_YBI',
       'neighbourhood_cleansed_Twin_Peaks',
       'neighbourhood_cleansed_Visitacion_Valley',
       'neighbourhood_cleansed_West_of_Twin_Peaks',
       'neighbourhood_cleansed_Western_Addition', 'zipcode_94014',
       'zipcode_94030', 'zipcode_94080', 'zipcode_94102', 'zipcode_94103',
       'zipcode_94104', 'zipcode_94105', 'zipcode_94107', 'zipcode_94108',
       'zipcode_94109', 'zipcode_94110', 'zipcode_94111', 'zipcode_94112',
       'zipcode_94113', 'zipcode_94114', 'zipcode_94116', 'zipcode_94117',
       'zipcode_94118', 'zipcode_94121', 'zipcode_94122', 'zipcode_94123',
       'zipcode_94124', 'zipcode_94127', 'zipcode_94129', 'zipcode_94130',
       'zipcode_94131', 'zipcode_94132', 'zipcode_94133', 'zipcode_94134',
       'zipcode_94158', 'latitude', 'longitude', 'is_location_exact_f',
       'is_location_exact_t', 'property_type_Aparthotel',
       'property_type_Apartment', 'property_type_Bed___Breakfast',
       'property_type_Bed_and_breakfast', 'property_type_Boat',
       'property_type_Boutique_hotel', 'property_type_Bungalow',
       'property_type_Bus', 'property_type_Cabin',
       'property_type_Camper_RV', 'property_type_Cave',
       'property_type_Condominium', 'property_type_Cottage',
       'property_type_Dome_house', 'property_type_Dorm',
       'property_type_Entire_Floor', 'property_type_Floor',
       'property_type_Guest_suite', 'property_type_Guesthouse',
       'property_type_Hostel', 'property_type_Hotel',
       'property_type_House', 'property_type_In_law',
       'property_type_Lighthouse', 'property_type_Loft',
       'property_type_Other', 'property_type_Resort',
       'property_type_Serviced_apartment', 'property_type_Tent',
       'property_type_Townhouse', 'property_type_Treehouse',
       'property_type_Villa', 'room_type_Entire_home_apt',
       'room_type_Hotel_room', 'room_type_Private_room',
       'room_type_Shared_room', 'accommodates', 'bathrooms', 'bedrooms',
       'beds', 'bed_type_Airbed', 'bed_type_Couch', 'bed_type_Futon',
       'bed_type_Pull_out_Sofa', 'bed_type_Real_Bed', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people',
       'minimum_nights', 'maximum_nights', 'number_of_reviews',
       'review_scores_accuracy_Bad', 'review_scores_accuracy_Good',
       'review_scores_accuracy_Missing', 'review_scores_accuracy_Perfect',
       'review_scores_cleanliness_Bad', 'review_scores_cleanliness_Good',
       'review_scores_cleanliness_Missing',
       'review_scores_cleanliness_Perfect', 'review_scores_checkin_Bad',
       'review_scores_checkin_Good', 'review_scores_checkin_Missing',
       'review_scores_checkin_Perfect', 'review_scores_communication_Bad',
       'review_scores_communication_Good',
       'review_scores_communication_Missing',
       'review_scores_communication_Perfect',
       'review_scores_location_Bad', 'review_scores_location_Good',
       'review_scores_location_Missing', 'review_scores_location_Perfect',
       'review_scores_value_Bad', 'review_scores_value_Good',
       'review_scores_value_Missing', 'review_scores_value_Perfect',
       'instant_bookable_f', 'instant_bookable_t', 'cancellation_policy',
       'require_guest_profile_picture_f',
       'require_guest_profile_picture_t',
       'require_guest_phone_verification_f',
       'require_guest_phone_verification_t',
       'calculated_host_listings_count', 'reviews_per_month_1',
       'reviews_per_month_10', 'reviews_per_month_2',
       'reviews_per_month_3', 'reviews_per_month_4',
       'reviews_per_month_5', 'reviews_per_month_6',
       'reviews_per_month_7', 'reviews_per_month_8',
       'reviews_per_month_9', 'reviews_per_month_Missing',
       'host_seniority', 'accommodates.norm', 'host_about_len',
       'description_len', 'summary_len', 'total_amenities',
       'price_per_person', 'amenities_Freestreetparking',
       'amenities_Familykidfriendly', 'amenities_CableTV',
       'amenities_Internet', 'amenities_Firstaidkit',
       'amenities_Laptopfriendlyworkspace', 'amenities_Fireextinguisher',
       'amenities_Iron', 'amenities_Hairdryer', 'amenities_Dryer',
       'amenities_Washer', 'amenities_Wifi',
       'amenities_Carbonmonoxidedetector', 'amenities_Hangers',
       'amenities_TV', 'amenities_Shampoo', 'amenities_Kitchen',
       'amenities_Smokedetector', 'amenities_Essentials',
       'amenities_Heating'], dtype=object)

We will add these variables to our variable selection table

In [13]:
varSel['Univarable'] = 0
varSel.loc[varSel['Variable'].isin(vn1), 'Univarable'] = 1
varSel

                              Variable  Univarable
0                           week_num_1           1
1                          week_num_10           1
2                          week_num_11           1
3                          week_num_12           1
4                          week_num_13           1
5                          week_num_14           1
6                          week_num_15           1
7                          week_num_16           1
8                          week_num_17           1
9                          week_num_18           1
10                         week_num_19           1
11                          week_num_2           1
12                         week_num_20           1
13                         week_num_21           1
14                         week_num_22           0
15                         week_num_23           1
16                         week_num_24           1
17                         week_num_25           1
18                         week_num_26           1
19                         week_num_27           1
20                         week_num_28           1
21                         week_num_29           1
22                          week_num_3           1
23                         week_num_30           1
24                         week_num_31           1
25                         week_num_32           1
26                         week_num_33           1
27                         week_num_34           1
28                         week_num_35           1
29                         week_num_36           1
..                                 ...         ...
245                reviews_per_month_8           1
246                reviews_per_month_9           1
247          reviews_per_month_Missing           1
248                     host_seniority           1
249                  accommodates.norm           1
250                     host_about_len           1
251                    description_len           1
252                        summary_len           1
253                    total_amenities           1
254                   price_per_person           1
255        amenities_Freestreetparking           1
256        amenities_Familykidfriendly           1
257                  amenities_CableTV           1
258                 amenities_Internet           1
259              amenities_Firstaidkit           1
260  amenities_Laptopfriendlyworkspace           1
261         amenities_Fireextinguisher           1
262                     amenities_Iron           1
263                amenities_Hairdryer           1
264                    amenities_Dryer           1
265                   amenities_Washer           1
266                     amenities_Wifi           1
267   amenities_Carbonmonoxidedetector           1
268                  amenities_Hangers           1
269                       amenities_TV           1
270                  amenities_Shampoo           1
271                  amenities_Kitchen           1
272            amenities_Smokedetector           1
273               amenities_Essentials           1
274                  amenities_Heating           1

[275 rows x 2 columns]

## Multivariable Analysis

In [14]:
### drop na
df = df.dropna()

In [15]:
df.head()

,week_num_1,week_num_10,week_num_11,week_num_12,week_num_13,week_num_14,week_num_15,week_num_16,week_num_17,week_num_18,...,amenities_Washer,amenities_Wifi,amenities_Carbonmonoxidedetector,amenities_Hangers,amenities_TV,amenities_Shampoo,amenities_Kitchen,amenities_Smokedetector,amenities_Essentials,amenities_Heating
0,0,0,0,1,0,0,0,0,0,0,...,0,1,1,1,1,1,0,1,1,1
1,0,0,0,0,1,0,0,0,0,0,...,0,1,1,1,1,1,0,1,1,1
2,0,0,1,0,0,0,0,0,0,0,...,0,1,1,1,1,1,0,1,1,1
3,0,0,0,0,0,1,0,0,0,0,...,0,1,1,1,1,1,0,1,1,1
4,0,0,1,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,1,1

In [16]:
## remove unnecessary vars
X = df.drop(['occupied_cat'], axis=1)
X.head()

,week_num_1,week_num_10,week_num_11,week_num_12,week_num_13,week_num_14,week_num_15,week_num_16,week_num_17,week_num_18,...,amenities_Washer,amenities_Wifi,amenities_Carbonmonoxidedetector,amenities_Hangers,amenities_TV,amenities_Shampoo,amenities_Kitchen,amenities_Smokedetector,amenities_Essentials,amenities_Heating
0,0,0,0,1,0,0,0,0,0,0,...,0,1,1,1,1,1,0,1,1,1
1,0,0,0,0,1,0,0,0,0,0,...,0,1,1,1,1,1,0,1,1,1
2,0,0,1,0,0,0,0,0,0,0,...,0,1,1,1,1,1,0,1,1,1
3,0,0,0,0,0,1,0,0,0,0,...,0,1,1,1,1,1,0,1,1,1
4,0,0,1,0,0,0,0,0,0,0,...,1,1,1,1,1,0,1,1,1,1

In [17]:
y = df.loc[:, 'occupied_cat']
print([X.shape,y.shape])

[(176451, 275), (176451,)]

In [18]:
varSel

                              Variable  Univarable
0                           week_num_1           1
1                          week_num_10           1
2                          week_num_11           1
3                          week_num_12           1
4                          week_num_13           1
5                          week_num_14           1
6                          week_num_15           1
7                          week_num_16           1
8                          week_num_17           1
9                          week_num_18           1
10                         week_num_19           1
11                          week_num_2           1
12                         week_num_20           1
13                         week_num_21           1
14                         week_num_22           0
15                         week_num_23           1
16                         week_num_24           1
17                         week_num_25           1
18                         week_num_26           1
19                         week_num_27           1
20                         week_num_28           1
21                         week_num_29           1
22                          week_num_3           1
23                         week_num_30           1
24                         week_num_31           1
25                         week_num_32           1
26                         week_num_33           1
27                         week_num_34           1
28                         week_num_35           1
29                         week_num_36           1
..                                 ...         ...
245                reviews_per_month_8           1
246                reviews_per_month_9           1
247          reviews_per_month_Missing           1
248                     host_seniority           1
249                  accommodates.norm           1
250                     host_about_len           1
251                    description_len           1
252                        summary_len           1
253                    total_amenities           1
254                   price_per_person           1
255        amenities_Freestreetparking           1
256        amenities_Familykidfriendly           1
257                  amenities_CableTV           1
258                 amenities_Internet           1
259              amenities_Firstaidkit           1
260  amenities_Laptopfriendlyworkspace           1
261         amenities_Fireextinguisher           1
262                     amenities_Iron           1
263                amenities_Hairdryer           1
264                    amenities_Dryer           1
265                   amenities_Washer           1
266                     amenities_Wifi           1
267   amenities_Carbonmonoxidedetector           1
268                  amenities_Hangers           1
269                       amenities_TV           1
270                  amenities_Shampoo           1
271                  amenities_Kitchen           1
272            amenities_Smokedetector           1
273               amenities_Essentials           1
274                  amenities_Heating           1

[275 rows x 2 columns]

### Variable Selection using LASSO (L1 penalization)

In [19]:
from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel

lassomod = Lasso(alpha=0.01).fit(X, y)

In [20]:
model = SelectFromModel(lassomod, prefit=True)
model.get_support()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False])

In [21]:
len(model.get_support())
varSel.shape
X.shape

(176451, 275)

In [22]:
varSel['Lasso'] = model.get_support().astype('int64')
varSel

                              Variable  Univarable  Lasso
0                           week_num_1           1      0
1                          week_num_10           1      0
2                          week_num_11           1      0
3                          week_num_12           1      0
4                          week_num_13           1      0
5                          week_num_14           1      0
6                          week_num_15           1      0
7                          week_num_16           1      0
8                          week_num_17           1      0
9                          week_num_18           1      0
10                         week_num_19           1      0
11                          week_num_2           1      0
12                         week_num_20           1      0
13                         week_num_21           1      0
14                         week_num_22           0      0
15                         week_num_23           1      0
16                         week_num_24           1      0
17                         week_num_25           1      0
18                         week_num_26           1      0
19                         week_num_27           1      0
20                         week_num_28           1      0
21                         week_num_29           1      0
22                          week_num_3           1      0
23                         week_num_30           1      0
24                         week_num_31           1      0
25                         week_num_32           1      0
26                         week_num_33           1      0
27                         week_num_34           1      0
28                         week_num_35           1      0
29                         week_num_36           1      0
..                                 ...         ...    ...
245                reviews_per_month_8           1      0
246                reviews_per_month_9           1      0
247          reviews_per_month_Missing           1      0
248                     host_seniority           1      1
249                  accommodates.norm           1      0
250                     host_about_len           1      1
251                    description_len           1      1
252                        summary_len           1      1
253                    total_amenities           1      1
254                   price_per_person           1      0
255        amenities_Freestreetparking           1      0
256        amenities_Familykidfriendly           1      0
257                  amenities_CableTV           1      0
258                 amenities_Internet           1      0
259              amenities_Firstaidkit           1      0
260  amenities_Laptopfriendlyworkspace           1      0
261         amenities_Fireextinguisher           1      0
262                     amenities_Iron           1      0
263                amenities_Hairdryer           1      0
264                    amenities_Dryer           1      0
265                   amenities_Washer           1      0
266                     amenities_Wifi           1      1
267   amenities_Carbonmonoxidedetector           1      0
268                  amenities_Hangers           1      0
269                       amenities_TV           1      0
270                  amenities_Shampoo           1      0
271                  amenities_Kitchen           1      0
272            amenities_Smokedetector           1      0
273               amenities_Essentials           1      0
274                  amenities_Heating           1      0

[275 rows x 3 columns]

### Variable Selection using Random Forest

In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

rfmod = RandomForestClassifier().fit(X, y)
#rfmod.feature_importances_

C:\Users\vladip\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [24]:
model = SelectFromModel(rfmod, prefit=True)
model.get_support()

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True, False,  True,  True,  True, False,
       False,  True,  True, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True, False, False, False, False, False,  True, False, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
        True, False,  True,  True, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True, False, False,  True, False,  True, False,
       False, False,  True, False, False])

In [25]:
varSel['RandomForest'] = model.get_support().astype('int64')
varSel

                              Variable  Univarable  Lasso  RandomForest
0                           week_num_1           1      0             0
1                          week_num_10           1      0             1
2                          week_num_11           1      0             1
3                          week_num_12           1      0             1
4                          week_num_13           1      0             1
5                          week_num_14           1      0             1
6                          week_num_15           1      0             1
7                          week_num_16           1      0             1
8                          week_num_17           1      0             1
9                          week_num_18           1      0             1
10                         week_num_19           1      0             1
11                          week_num_2           1      0             0
12                         week_num_20           1      0             1
13                         week_num_21           1      0             0
14                         week_num_22           0      0             1
15                         week_num_23           1      0             1
16                         week_num_24           1      0             1
17                         week_num_25           1      0             0
18                         week_num_26           1      0             0
19                         week_num_27           1      0             1
20                         week_num_28           1      0             1
21                         week_num_29           1      0             0
22                          week_num_3           1      0             0
23                         week_num_30           1      0             0
24                         week_num_31           1      0             1
25                         week_num_32           1      0             1
26                         week_num_33           1      0             1
27                         week_num_34           1      0             1
28                         week_num_35           1      0             1
29                         week_num_36           1      0             1
..                                 ...         ...    ...           ...
245                reviews_per_month_8           1      0             0
246                reviews_per_month_9           1      0             0
247          reviews_per_month_Missing           1      0             0
248                     host_seniority           1      1             1
249                  accommodates.norm           1      0             1
250                     host_about_len           1      1             1
251                    description_len           1      1             0
252                        summary_len           1      1             1
253                    total_amenities           1      1             1
254                   price_per_person           1      0             1
255        amenities_Freestreetparking           1      0             1
256        amenities_Familykidfriendly           1      0             1
257                  amenities_CableTV           1      0             0
258                 amenities_Internet           1      0             1
259              amenities_Firstaidkit           1      0             1
260  amenities_Laptopfriendlyworkspace           1      0             1
261         amenities_Fireextinguisher           1      0             1
262                     amenities_Iron           1      0             1
263                amenities_Hairdryer           1      0             1
264                    amenities_Dryer           1      0             0
265                   amenities_Washer           1      0             0
266                     amenities_Wifi           1      1             1
267   amenities_Carbonmonoxidedetector           1      0             0
268                  amenities_Hangers           1      0             1
269                       amenities_TV           1      0             0
270                  amenities_Shampoo           1      0             0
271                  amenities_Kitchen           1      0             0
272            amenities_Smokedetector           1      0             1
273               amenities_Essentials           1      0             0
274                  amenities_Heating           1      0             0

[275 rows x 4 columns]

### Variable Selection using Gradient Boosting classification

In [26]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.feature_selection import SelectFromModel

gbmod = GradientBoostingClassifier().fit(X, y)

In [27]:
model = SelectFromModel(gbmod, prefit=True)
model.get_support()

array([ True, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True,  True,  True, False, False, False, False, False,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False,  True,  True, False, False, False,  True, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False,  True, False, False])

In [28]:
varSel['GradientBoost'] = model.get_support().astype('int64')
varSel

,Variable,Univarable,Lasso,RandomForest,GradientBoost
0,week_num_1,1,0,0,1
1,week_num_10,1,0,1,0
2,week_num_11,1,0,1,0
3,week_num_12,1,0,1,0
4,week_num_13,1,0,1,0
5,week_num_14,1,0,1,0
6,week_num_15,1,0,1,0
7,week_num_16,1,0,1,0
8,week_num_17,1,0,1,0
9,week_num_18,1,0,1,0
10,week_num_19,1,0,1,0
11,week_num_2,1,0,0,1
12,week_num_20,1,0,1,0
13,week_num_21,1,0,0,0
14,week_num_22,0,0,1,0
15,week_num_23,1,0,1,0
16,week_num_24,1,0,1,0
17,week_num_25,1,0,0,0
18,week_num_26,1,0,0,0
19,week_num_27,1,0,1,0
20,week_num_28,1,0,1,0
21,week_num_29,1,0,0,0
22,week_num_3,1,0,0,0
23,week_num_30,1,0,0,0
24,week_num_31,1,0,1,0
25,week_num_32,1,0,1,0
26,week_num_33,1,0,1,0
27,week_num_34,1,0,1,0
28,week_num_35,1,0,1,0
29,week_num_36,1,0,1,0
...,...,...,...,...,...
245,reviews_per_month_8,1,0,0,0
246,reviews_per_month_9,1,0,0,0
247,reviews_per_month_Missing,1,0,0,0
248,host_seniority,1,1,1,1
249,accommodates.norm,1,0,1,0
250,host_about_len,1,1,1,0
251,description_len,1,1,0,0
252,summary_len,1,1,1,0
253,total_amenities,1,1,1,1
254,price_per_person,1,0,1,1
255,amenities_Freestreetparking,1,0,1,0
256,amenities_Familykidfriendly,1,0,1,0
257,amenities_CableTV,1,0,0,0
258,amenities_Internet,1,0,1,1
259,amenities_Firstaidkit,1,0,1,0
260,amenities_Laptopfriendlyworkspace,1,0,1,0
261,amenities_Fireextinguisher,1,0,1,0
262,amenities_Iron,1,0,1,0
263,amenities_Hairdryer,1,0,1,0
264,amenities_Dryer,1,0,0,0
265,amenities_Washer,1,0,0,0
266,amenities_Wifi,1,1,1,1
267,amenities_Carbonmonoxidedetector,1,0,0,0
268,amenities_Hangers,1,0,1,0
269,amenities_TV,1,0,0,0
270,amenities_Shampoo,1,0,0,0
271,amenities_Kitchen,1,0,0,0
272,amenities_Smokedetector,1,0,1,1
273,amenities_Essentials,1,0,0,0
274,amenities_Heating,1,0,0,0

### Variable Selection using SVM classification

In [29]:
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel

svmmod = LinearSVC(C=0.01, penalty="l1",dual=False).fit(X, y)

C:\Users\vladip\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

In [30]:
model = SelectFromModel(svmmod, prefit=True)
model.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False,  True, False, False, False, False, False,
        True,  True, False, False,  True,  True,  True, False,  True,
       False,  True,  True, False,  True,  True, False, False,  True,
        True, False, False,  True,  True,  True,  True, False, False,
       False,  True, False, False, False, False,  True,  True, False,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True, False,  True, False,  True,  True, False, False,
       False, False,  True,  True, False,  True, False, False, False,
       False, False, False, False,  True,  True,  True,  True, False,
        True, False, False,  True, False,  True, False, False, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False,  True, False,  True,  True,  True, False,
       False, False,  True,  True, False,  True,  True, False, False,
       False,  True, False, False,  True,  True, False, False,  True,
        True,  True,  True,  True, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [31]:
varSel['SVM'] = model.get_support().astype('int64')
varSel

,Variable,Univarable,Lasso,RandomForest,GradientBoost,SVM
0,week_num_1,1,0,0,1,1
1,week_num_10,1,0,1,0,1
2,week_num_11,1,0,1,0,1
3,week_num_12,1,0,1,0,1
4,week_num_13,1,0,1,0,1
5,week_num_14,1,0,1,0,1
6,week_num_15,1,0,1,0,1
7,week_num_16,1,0,1,0,1
8,week_num_17,1,0,1,0,1
9,week_num_18,1,0,1,0,1
10,week_num_19,1,0,1,0,1
11,week_num_2,1,0,0,1,1
12,week_num_20,1,0,1,0,1
13,week_num_21,1,0,0,0,1
14,week_num_22,0,0,1,0,1
15,week_num_23,1,0,1,0,1
16,week_num_24,1,0,1,0,1
17,week_num_25,1,0,0,0,1
18,week_num_26,1,0,0,0,1
19,week_num_27,1,0,1,0,1
20,week_num_28,1,0,1,0,1
21,week_num_29,1,0,0,0,1
22,week_num_3,1,0,0,0,1
23,week_num_30,1,0,0,0,1
24,week_num_31,1,0,1,0,1
25,week_num_32,1,0,1,0,1
26,week_num_33,1,0,1,0,1
27,week_num_34,1,0,1,0,0
28,week_num_35,1,0,1,0,1
29,week_num_36,1,0,1,0,1
...,...,...,...,...,...,...
245,reviews_per_month_8,1,0,0,0,1
246,reviews_per_month_9,1,0,0,0,0
247,reviews_per_month_Missing,1,0,0,0,1
248,host_seniority,1,1,1,1,1
249,accommodates.norm,1,0,1,0,1
250,host_about_len,1,1,1,0,1
251,description_len,1,1,0,0,1
252,summary_len,1,1,1,0,1
253,total_amenities,1,1,1,1,1
254,price_per_person,1,0,1,1,1
255,amenities_Freestreetparking,1,0,1,0,1
256,amenities_Familykidfriendly,1,0,1,0,1
257,amenities_CableTV,1,0,0,0,1
258,amenities_Internet,1,0,1,1,1
259,amenities_Firstaidkit,1,0,1,0,1
260,amenities_Laptopfriendlyworkspace,1,0,1,0,1
261,amenities_Fireextinguisher,1,0,1,0,1
262,amenities_Iron,1,0,1,0,1
263,amenities_Hairdryer,1,0,1,0,1
264,amenities_Dryer,1,0,0,0,1
265,amenities_Washer,1,0,0,0,1
266,amenities_Wifi,1,1,1,1,1
267,amenities_Carbonmonoxidedetector,1,0,0,0,1
268,amenities_Hangers,1,0,1,0,1
269,amenities_TV,1,0,0,0,1
270,amenities_Shampoo,1,0,0,0,1
271,amenities_Kitchen,1,0,0,0,1
272,amenities_Smokedetector,1,0,1,1,1
273,amenities_Essentials,1,0,0,0,1
274,amenities_Heating,1,0,0,0,1

### Summarization and Selection of Variables

In [32]:
varSel['Sum'] =  np.sum(varSel,axis=1)
varSel

,Variable,Univarable,Lasso,RandomForest,GradientBoost,SVM,Sum
0,week_num_1,1,0,0,1,1,3
1,week_num_10,1,0,1,0,1,3
2,week_num_11,1,0,1,0,1,3
3,week_num_12,1,0,1,0,1,3
4,week_num_13,1,0,1,0,1,3
5,week_num_14,1,0,1,0,1,3
6,week_num_15,1,0,1,0,1,3
7,week_num_16,1,0,1,0,1,3
8,week_num_17,1,0,1,0,1,3
9,week_num_18,1,0,1,0,1,3
10,week_num_19,1,0,1,0,1,3
11,week_num_2,1,0,0,1,1,3
12,week_num_20,1,0,1,0,1,3
13,week_num_21,1,0,0,0,1,2
14,week_num_22,0,0,1,0,1,2
15,week_num_23,1,0,1,0,1,3
16,week_num_24,1,0,1,0,1,3
17,week_num_25,1,0,0,0,1,2
18,week_num_26,1,0,0,0,1,2
19,week_num_27,1,0,1,0,1,3
20,week_num_28,1,0,1,0,1,3
21,week_num_29,1,0,0,0,1,2
22,week_num_3,1,0,0,0,1,2
23,week_num_30,1,0,0,0,1,2
24,week_num_31,1,0,1,0,1,3
25,week_num_32,1,0,1,0,1,3
26,week_num_33,1,0,1,0,1,3
27,week_num_34,1,0,1,0,0,2
28,week_num_35,1,0,1,0,1,3
29,week_num_36,1,0,1,0,1,3
...,...,...,...,...,...,...,...
245,reviews_per_month_8,1,0,0,0,1,2
246,reviews_per_month_9,1,0,0,0,0,1
247,reviews_per_month_Missing,1,0,0,0,1,2
248,host_seniority,1,1,1,1,1,5
249,accommodates.norm,1,0,1,0,1,3
250,host_about_len,1,1,1,0,1,4
251,description_len,1,1,0,0,1,3
252,summary_len,1,1,1,0,1,4
253,total_amenities,1,1,1,1,1,5
254,price_per_person,1,0,1,1,1,4
255,amenities_Freestreetparking,1,0,1,0,1,3
256,amenities_Familykidfriendly,1,0,1,0,1,3
257,amenities_CableTV,1,0,0,0,1,2
258,amenities_Internet,1,0,1,1,1,4
259,amenities_Firstaidkit,1,0,1,0,1,3
260,amenities_Laptopfriendlyworkspace,1,0,1,0,1,3
261,amenities_Fireextinguisher,1,0,1,0,1,3
262,amenities_Iron,1,0,1,0,1,3
263,amenities_Hairdryer,1,0,1,0,1,3
264,amenities_Dryer,1,0,0,0,1,2
265,amenities_Washer,1,0,0,0,1,2
266,amenities_Wifi,1,1,1,1,1,5
267,amenities_Carbonmonoxidedetector,1,0,0,0,1,2
268,amenities_Hangers,1,0,1,0,1,3
269,amenities_TV,1,0,0,0,1,2
270,amenities_Shampoo,1,0,0,0,1,2
271,amenities_Kitchen,1,0,0,0,1,2
272,amenities_Smokedetector,1,0,1,1,1,4
273,amenities_Essentials,1,0,0,0,1,2
274,amenities_Heating,1,0,0,0,1,2

In [33]:
varSel.groupby('Sum')['Variable'].count()

Sum
0     23
1     67
2    103
3     56
4     15
5     11
Name: Variable, dtype: int64

We can now decide a threshold for selecting our variables!

In [39]:
varSel[varSel.Sum > 2].Variable.values

array(['week_num_1', 'week_num_10', 'week_num_11', 'week_num_12',
       'week_num_13', 'week_num_14', 'week_num_15', 'week_num_16',
       'week_num_17', 'week_num_18', 'week_num_19', 'week_num_2',
       'week_num_20', 'week_num_23', 'week_num_24', 'week_num_27',
       'week_num_28', 'week_num_31', 'week_num_32', 'week_num_33',
       'week_num_35', 'week_num_36', 'week_num_37', 'week_num_38',
       'week_num_41', 'week_num_42', 'week_num_48', 'week_num_50',
       'week_num_51', 'week_num_52', 'week_num_53', 'week_num_6',
       'week_num_7', 'week_num_8', 'week_num_9', 'avg_price', 'min_price',
       'max_price', 'host_is_superhost_f', 'host_is_superhost_t',
       'host_identity_verified_f', 'host_identity_verified_t', 'latitude',
       'longitude', 'property_type_Boutique_hotel', 'property_type_Hotel',
       'property_type_Serviced_apartment', 'room_type_Entire_home_apt',
       'accommodates', 'bedrooms', 'beds', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people',
       'minimum_nights', 'maximum_nights', 'number_of_reviews',
       'review_scores_value_Perfect', 'instant_bookable_f',
       'instant_bookable_t', 'cancellation_policy',
       'calculated_host_listings_count', 'reviews_per_month_1',
       'host_seniority', 'accommodates.norm', 'host_about_len',
       'description_len', 'summary_len', 'total_amenities',
       'price_per_person', 'amenities_Freestreetparking',
       'amenities_Familykidfriendly', 'amenities_Internet',
       'amenities_Firstaidkit', 'amenities_Laptopfriendlyworkspace',
       'amenities_Fireextinguisher', 'amenities_Iron',
       'amenities_Hairdryer', 'amenities_Wifi', 'amenities_Hangers',
       'amenities_Smokedetector'], dtype=object)